//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DL.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitAspNetRoleEntityMappings();
			InitAspNetRoleClaimEntityMappings();
			InitAspNetUserEntityMappings();
			InitAspNetUserClaimEntityMappings();
			InitAspNetUserLoginEntityMappings();
			InitAspNetUserRoleEntityMappings();
			InitAspNetUserTokenEntityMappings();
			InitAuthorEntityMappings();
			InitBookEntityMappings();
			InitEfmigrationsHistoryEntityMappings();
		}

		/// <summary>Inits AspNetRoleEntity's mappings</summary>
		private void InitAspNetRoleEntityMappings()
		{
			this.AddElementMapping("AspNetRoleEntity", @"BookStoreDB", @"dbo", "AspNetRoles", 4, 0);
			this.AddElementFieldMapping("AspNetRoleEntity", "ConcurrencyStamp", "ConcurrencyStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetRoleEntity", "Id", "Id", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetRoleEntity", "Name", "Name", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetRoleEntity", "NormalizedName", "NormalizedName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetRoleClaimEntity's mappings</summary>
		private void InitAspNetRoleClaimEntityMappings()
		{
			this.AddElementMapping("AspNetRoleClaimEntity", @"BookStoreDB", @"dbo", "AspNetRoleClaims", 4, 0);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "ClaimType", "ClaimType", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "ClaimValue", "ClaimValue", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AspNetRoleClaimEntity", "RoleId", "RoleId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserEntity's mappings</summary>
		private void InitAspNetUserEntityMappings()
		{
			this.AddElementMapping("AspNetUserEntity", @"BookStoreDB", @"dbo", "AspNetUsers", 17, 0);
			this.AddElementFieldMapping("AspNetUserEntity", "AccessFailedCount", "AccessFailedCount", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("AspNetUserEntity", "ConcurrencyStamp", "ConcurrencyStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserEntity", "Email", "Email", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserEntity", "EmailConfirmed", "EmailConfirmed", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 3);
			this.AddElementFieldMapping("AspNetUserEntity", "FirstName", "FirstName", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("AspNetUserEntity", "Id", "Id", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("AspNetUserEntity", "LastName", "LastName", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("AspNetUserEntity", "LockoutEnabled", "LockoutEnabled", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 7);
			this.AddElementFieldMapping("AspNetUserEntity", "LockoutEnd", "LockoutEnd", true, "DateTimeOffset", 0, 0, 0, false, "", null, typeof(System.DateTimeOffset), 8);
			this.AddElementFieldMapping("AspNetUserEntity", "NormalizedEmail", "NormalizedEmail", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("AspNetUserEntity", "NormalizedUserName", "NormalizedUserName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("AspNetUserEntity", "PasswordHash", "PasswordHash", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("AspNetUserEntity", "PhoneNumber", "PhoneNumber", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("AspNetUserEntity", "PhoneNumberConfirmed", "PhoneNumberConfirmed", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 13);
			this.AddElementFieldMapping("AspNetUserEntity", "SecurityStamp", "SecurityStamp", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("AspNetUserEntity", "TwoFactorEnabled", "TwoFactorEnabled", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 15);
			this.AddElementFieldMapping("AspNetUserEntity", "UserName", "UserName", true, "NVarChar", 256, 0, 0, false, "", null, typeof(System.String), 16);
		}

		/// <summary>Inits AspNetUserClaimEntity's mappings</summary>
		private void InitAspNetUserClaimEntityMappings()
		{
			this.AddElementMapping("AspNetUserClaimEntity", @"BookStoreDB", @"dbo", "AspNetUserClaims", 4, 0);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "ClaimType", "ClaimType", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "ClaimValue", "ClaimValue", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AspNetUserClaimEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserLoginEntity's mappings</summary>
		private void InitAspNetUserLoginEntityMappings()
		{
			this.AddElementMapping("AspNetUserLoginEntity", @"BookStoreDB", @"dbo", "AspNetUserLogins", 4, 0);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "LoginProvider", "LoginProvider", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "ProviderDisplayName", "ProviderDisplayName", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "ProviderKey", "ProviderKey", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserLoginEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AspNetUserRoleEntity's mappings</summary>
		private void InitAspNetUserRoleEntityMappings()
		{
			this.AddElementMapping("AspNetUserRoleEntity", @"BookStoreDB", @"dbo", "AspNetUserRoles", 2, 0);
			this.AddElementFieldMapping("AspNetUserRoleEntity", "RoleId", "RoleId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserRoleEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits AspNetUserTokenEntity's mappings</summary>
		private void InitAspNetUserTokenEntityMappings()
		{
			this.AddElementMapping("AspNetUserTokenEntity", @"BookStoreDB", @"dbo", "AspNetUserTokens", 4, 0);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "LoginProvider", "LoginProvider", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "Name", "Name", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "UserId", "UserId", false, "NVarChar", 450, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AspNetUserTokenEntity", "Value", "Value", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits AuthorEntity's mappings</summary>
		private void InitAuthorEntityMappings()
		{
			this.AddElementMapping("AuthorEntity", @"BookStoreDB", @"dbo", "Authors", 4, 0);
			this.AddElementFieldMapping("AuthorEntity", "Bio", "Bio", true, "NChar", 250, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AuthorEntity", "FirstName", "FirstName", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("AuthorEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("AuthorEntity", "LastName", "LastName", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits BookEntity's mappings</summary>
		private void InitBookEntityMappings()
		{
			this.AddElementMapping("BookEntity", @"BookStoreDB", @"dbo", "Books", 8, 0);
			this.AddElementFieldMapping("BookEntity", "AuthorId", "AuthorId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("BookEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("BookEntity", "Image", "Image", true, "NVarChar", 250, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("BookEntity", "Isbn", "ISBN", false, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("BookEntity", "Price", "Price", true, "Decimal", 0, 18, 2, false, "", null, typeof(System.Decimal), 4);
			this.AddElementFieldMapping("BookEntity", "Summary", "Summary", true, "NVarChar", 250, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("BookEntity", "Title", "Title", true, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("BookEntity", "Year", "Year", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
		}

		/// <summary>Inits EfmigrationsHistoryEntity's mappings</summary>
		private void InitEfmigrationsHistoryEntityMappings()
		{
			this.AddElementMapping("EfmigrationsHistoryEntity", @"BookStoreDB", @"dbo", "__EFMigrationsHistory", 2, 0);
			this.AddElementFieldMapping("EfmigrationsHistoryEntity", "MigrationId", "MigrationId", false, "NVarChar", 150, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("EfmigrationsHistoryEntity", "ProductVersion", "ProductVersion", false, "NVarChar", 32, 0, 0, false, "", null, typeof(System.String), 1);
		}

	}
}
