//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DL.HelperClasses;
using DL.FactoryClasses;
using DL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'EfmigrationsHistory'.<br/><br/></summary>
	[Serializable]
	public partial class EfmigrationsHistoryEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static EfmigrationsHistoryEntityStaticMetaData _staticMetaData = new EfmigrationsHistoryEntityStaticMetaData();
		private static EfmigrationsHistoryRelations _relationsFactory = new EfmigrationsHistoryRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class EfmigrationsHistoryEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public EfmigrationsHistoryEntityStaticMetaData()
			{
				SetEntityCoreInfo("EfmigrationsHistoryEntity", InheritanceHierarchyType.None, false, (int)DL.EntityType.EfmigrationsHistoryEntity, typeof(EfmigrationsHistoryEntity), typeof(EfmigrationsHistoryEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static EfmigrationsHistoryEntity()
		{
		}

		/// <summary> CTor</summary>
		public EfmigrationsHistoryEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public EfmigrationsHistoryEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this EfmigrationsHistoryEntity</param>
		public EfmigrationsHistoryEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="migrationId">PK value for EfmigrationsHistory which data should be fetched into this EfmigrationsHistory object</param>
		public EfmigrationsHistoryEntity(System.String migrationId) : this(migrationId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="migrationId">PK value for EfmigrationsHistory which data should be fetched into this EfmigrationsHistory object</param>
		/// <param name="validator">The custom validator object for this EfmigrationsHistoryEntity</param>
		public EfmigrationsHistoryEntity(System.String migrationId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.MigrationId = migrationId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected EfmigrationsHistoryEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this EfmigrationsHistoryEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static EfmigrationsHistoryRelations Relations { get { return _relationsFactory; } }

		/// <summary>The MigrationId property of the Entity EfmigrationsHistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "__EFMigrationsHistory"."MigrationId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String MigrationId
		{
			get { return (System.String)GetValue((int)EfmigrationsHistoryFieldIndex.MigrationId, true); }
			set	{ SetValue((int)EfmigrationsHistoryFieldIndex.MigrationId, value); }
		}

		/// <summary>The ProductVersion property of the Entity EfmigrationsHistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "__EFMigrationsHistory"."ProductVersion".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 32.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ProductVersion
		{
			get { return (System.String)GetValue((int)EfmigrationsHistoryFieldIndex.ProductVersion, true); }
			set	{ SetValue((int)EfmigrationsHistoryFieldIndex.ProductVersion, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace DL
{
	public enum EfmigrationsHistoryFieldIndex
	{
		///<summary>MigrationId. </summary>
		MigrationId,
		///<summary>ProductVersion. </summary>
		ProductVersion,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: EfmigrationsHistory. </summary>
	public partial class EfmigrationsHistoryRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticEfmigrationsHistoryRelations
	{

		/// <summary>CTor</summary>
		static StaticEfmigrationsHistoryRelations() { }
	}
}
